### ISSUE TITLE
Total approved cost is zero if you get a validation error

### ISSUE THREAD

**Issue by msjhall138** [ministryofjustice/apvs-internal-web#206]
If you approve all costs but then get a validation error then Total approved cost resets to zero even though all costs say approve.

Do not know if this effects the approved cost when entering in the DB, but dont think so, I think it is to do with the front end JS showing the total approved

![screen shot 2017-01-16 at 15 45 12](https://cloud.githubusercontent.com/assets/5646670/21989470/e3bcab6a-dc02-11e6-9d4b-154496df2e7a.png)

**Comment by hvekriya** [comment]
This wont affect the db however I did try to fix it with front-end but was unsuccessful. That is happening due to page not being reloaded and rather being redirected. There is front-end code there already which runs on page load however in this case the page is not getting loaded as it was already loaded before so javascript is not getting run again

Possible fix is to reload the page on error or assigning the approved cost value sent to server back to total approved cost text on validation error.

**Comment by stevenalexander** [comment]
verified
